AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false