AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false