production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
development:
  clients:
    default:
      database: etho_api_development
      hosts:
        - localhost:27017
      options:
test:
  clients:
    default:
      database: etho_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
